#
# Jailhouse, a Linux-based partitioning hypervisor
#
# Copyright (c) Siemens AG, 2014, 2015
#
# Authors:
#  Jan Kiszka <jan.kiszka@siemens.com>
#
# This work is licensed under the terms of the GNU GPL, version 2.  See
# the COPYING file in the top-level directory.
#

language: c

compiler:
  - gcc

env:
  global:
    - secure: "HeNK8vFhW6656FoEc05SWwjorvMZWkUTIioHBJoX+s59uQ6MlgyPNnro8FrrcX/fNWLDNRrzl9U05423JVMWwjOuov6MgShDJkG/imadVO8Y+ZIsKdefAp/DsUhIhsnRNh8+bxUStdFAVatMvPf/ZWuEk0K3BC95yWK1VXE73ZQ="
  matrix:
    - VARIANT=x86 ARCH=x86_64 CROSS_COMPILE=

install:
  - echo "deb http://archive.ubuntu.com/ubuntu utopic main restricted" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-mako gcc-arm-linux-gnueabihf make
  - cd ci
  - wget -q http://www.kiszka.org/downloads/travis-ci/kernel-build.tar.xz
  - tar xJf kernel-build.tar.xz
  - cd ..

script:
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then
        cp ci/jailhouse-config-${VARIANT}.h hypervisor/include/jailhouse/config.h;
        make KDIR=ci/linux/build-${VARIANT} ARCH=${ARCH} CROSS_COMPILE=${CROSS_COMPILE};
    fi

addons:
  coverity_scan:
    project:
      name: "siemens/jailhouse"
    notification_email: jan.kiszka@siemens.com
    build_command_prepend: "cov-configure --comptype gcc --compiler ${CROSS_COMPILE}gcc --template && cp ci/jailhouse-config-${VARIANT}.h hypervisor/include/jailhouse/config.h"
    build_command: "make KDIR=ci/linux/build-${VARIANT} ARCH=${ARCH} CROSS_COMPILE=${CROSS_COMPILE}"
    branch_pattern: coverity_scan

matrix:
  include:
    - env: VARIANT=banana-pi ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-
    - env: VARIANT=vexpress ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-
